# Generated by Django 4.2.15 on 2024-08-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('initial_date', models.DateTimeField()),
                ('final_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
    ]
